Add new getPegoutCreationRskTxHashByBtcTxHash bridge method
rsksmart/precompiled-abis pull request #48
Opened 2022-09-09 11:53 UTC by nathanieliov

2022-09-09 12:55 UTC, marcos-iov requested changes

2022-09-09 12:55 UTC, marcos-iov commented on abis/bridge.json
> +        "type": "bytes"
I think this was bytes32, wasn't it?

2022-09-09 12:55 UTC, marcos-iov commented on abis/bridge.json
> +    "inputs": [],
Missing the function input

2022-09-09 15:29 UTC, nathanieliov commented on abis/bridge.json
> +        "type": "bytes"
Good catch.

2022-09-12 18:08 UTC, marcos-iov approved these changes

2022-09-13 12:15 UTC, kelvinator07 approved these changes

2022-09-13 12:16 UTC, merged